name: Lint

on: [push]

jobs:
  build:
    name: Run lint checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
